# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtWidgets, QtCore, QtGui
from PyQt6.QtGui import QFont, QPixmap
from PyQt6.QtWidgets import QApplication, QMainWindow, QFileDialog
import numpy as np
import PIL
import tensorflow as tf
import sys
import cv2
import os
import glob
import shutil


class Ui_MainWindow(object):
    def __init__(self):
        super(Ui_MainWindow,self).__init__()
        self.model = tf.keras.models.load_model('.\\model.h5')
        self.class_names = ['1', '2', '3', '4', '5', '6', '7', '8']
        #self.setupUi(MainWindow)

    def getpose(self, filepath):
        res = 50
        im = PIL.Image.open(filepath)
        im = im.convert('RGB')
        im = im.resize((res, res), PIL.Image.Resampling.LANCZOS)
        im = np.asarray(im)
        im = im/255.
        im = im.reshape((1, res, res, 3))
        pred = self.model.predict(im, verbose=0)
        pred_class = self.class_names[np.argmax(pred)]
        pred_class = pred_class.replace('_', ' ')
        os.remove(filepath)
        return pred_class

    def load(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        filepath, _ = QFileDialog.getOpenFileName(self, "QFileDialog.getOpenFileName()", "", "All Files (*)",
                                                  options=options)
        if filepath:
            original_fp = filepath
            new_file = '.\\pic.' + filepath.split('.')[-1]
            if os.path.exists(new_file):
                os.remove(new_file)
            shutil.copy(filepath, new_file)
            filepath = new_file
            self.filepath = filepath
            self.pic.setText(original_fp)
            self.pic.adjustSize()
            self.label.setText(self.getpose(filepath))
            self.label.adjustSize()

        pass

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 796)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(410, 590, 181, 81))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 30, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAcceptDrops(False)
        self.label.setLineWidth(1)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 180, 201, 22))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 50, 71, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pic = QtWidgets.QLabel(parent=self.centralwidget)
        self.pic.setGeometry(QtCore.QRect(340, 150, 501, 401))
        self.pic.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"color: rgb(255, 255, 127);")
        self.pic.setObjectName("pic")
        self.eticetka = QtWidgets.QLabel(parent=self.centralwidget)
        self.eticetka.setGeometry(QtCore.QRect(260, 50, 91, 81))
        self.eticetka.setObjectName("eticetka")
        self.navs = QtWidgets.QLabel(parent=self.centralwidget)
        self.navs.setGeometry(QtCore.QRect(110, 570, 55, 16))
        self.navs.setObjectName("navs")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Тест приложения на Python"))
        self.pushButton.setText(_translate("MainWindow", "Выбрать файл"))
        self.label.setText(_translate("MainWindow", "Дорожный патруль"))
        self.pushButton_2.setText(_translate("MainWindow", "Каталог"))
        self.pic.setText(_translate("MainWindow", "TextLabel"))
        self.eticetka.setText(_translate("MainWindow", "TextLabel"))
        self.navs.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
